export const vocabulary = [
    //Colors
    { 'de': 'rot', 'en': 'red' },
    { 'de': 'rosa', 'en': 'pink' },
    { 'de': 'blau', 'en': 'blue' },
    { 'de': 'grün', 'en': 'green' },
    { 'de': 'gelb', 'en': 'yellow' },
    { 'de': 'orange', 'en': 'orange' },
    { 'de': 'braun', 'en': 'brown' },
    { 'de': 'weiß', 'en': 'white' },
    { 'de': 'schwarz', 'en': 'black' },
    { 'de': 'grau', 'en': 'gray' },
    { 'de': 'silber', 'en': 'silver' },

    //Weekdays
    { 'de': 'Montag', 'en': 'Monday' },
    { 'de': 'Dienstag', 'en': 'Tuesday' },
    { 'de': 'Mittwoch', 'en': 'Wednesday' },
    { 'de': 'Donnerstag', 'en': 'Thursday' },
    { 'de': 'Freitag', 'en': 'Friday' },
    { 'de': 'Samstag', 'en': 'Saturday' },
    { 'de': 'Sonntag', 'en': 'Sunday' },

    //Fruit
    { 'de_art': 'der', 'de': 'Apfel', 'en': 'apple', 'de_plu': 'die Äpfel' },
    { 'de_art': 'die', 'de': 'Ananas', 'en': 'pineapple', 'de_plu': 'die Ananasse' },
    { 'de_art': 'die', 'de': 'Banane', 'en': 'banana', 'de_plu': 'die Bananen' },
    { 'de_art': 'die', 'de': 'Birne', 'en': 'pear', 'de_plu': 'die Birnen' },
    { 'de_art': 'die', 'de': 'Erdbeere', 'en': 'strawberry', 'de_plu': 'die Erdbeeren' },
    { 'de_art': 'die', 'de': 'Kirsche', 'en': 'cherry', 'de_plu': 'die Kirschen' },
    { 'de_art': 'die', 'de': 'Melone', 'en': 'melon', 'de_plu': 'die Melonen' },
    { 'de_art': 'die', 'de': 'Orange', 'en': 'orange', 'de_plu': 'die Orangen' },
    { 'de_art': 'der', 'de': 'Pfirsich', 'en': 'peach', 'de_plu': 'die Pfirsiche' },
    //Family
    { 'de_art': 'die', 'de': 'Eltern', 'en': 'parents', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Mutter', 'en': 'mother', 'de_plu': 'die Mütter' },
    { 'de_art': 'der', 'de': 'Vater', 'en': 'father', 'de_plu': 'die Väter' },
    { 'de_art': 'die', 'de': 'Geschwister', 'en': 'siblings', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Schwester', 'en': 'sister', 'de_plu': 'die Schwestern' },
    { 'de_art': 'der', 'de': 'Bruder', 'en': 'brother', 'de_plu': 'die Brüder' },
    //Verbs
    { 'de_art': '', 'de': 'antworten', 'en': 'to answer', 'de_plu': '' },
    { 'de_art': '', 'de': 'arbeiten', 'en': 'to work', 'de_plu': '' },
    { 'de_art': '', 'de': 'bedeuten', 'en': 'to mean, signify', 'de_plu': '' },
    { 'de_art': '', 'de': 'beginnen', 'en': 'to begin', 'de_plu': '' },
    { 'de_art': '', 'de': 'bekommen', 'en': 'to get, receive', 'de_plu': '' },
    { 'de_art': '', 'de': 'bestellen', 'en': 'to order', 'de_plu': '' },
    { 'de_art': '', 'de': 'besuchen', 'en': 'to visit', 'de_plu': '' },
    { 'de_art': '', 'de': 'bezahlen', 'en': 'to pay', 'de_plu': '' },
    { 'de_art': '', 'de': 'bleiben', 'en': 'to stay, remain', 'de_plu': '' },
    { 'de_art': '', 'de': 'bringen', 'en': 'to bring, take', 'de_plu': '' },
    { 'de_art': '', 'de': 'danken', 'en': 'to thank', 'de_plu': '' },
    { 'de_art': '', 'de': 'denken', 'en': 'to think', 'de_plu': '' },
    { 'de_art': '', 'de': 'essen', 'en': 'to eat', 'de_plu': '' },
    { 'de_art': '', 'de': 'fahren', 'en': 'to travel, drive, go', 'de_plu': '' },
    { 'de_art': '', 'de': 'finden', 'en': 'to find', 'de_plu': '' },
    { 'de_art': '', 'de': 'fliegen', 'en': 'to fly', 'de_plu': '' },
    { 'de_art': '', 'de': 'fragen', 'en': 'to ask', 'de_plu': '' },
    { 'de_art': '', 'de': 'geben', 'en': 'to give', 'de_plu': '' },
    { 'de_art': '', 'de': 'gehen', 'en': 'to go', 'de_plu': '' },
    { 'de_art': '', 'de': 'helgfen', 'en': 'to help', 'de_plu': '' },
    { 'de_art': '', 'de': 'zuhören', 'en': 'to hear, listen', 'de_plu': '' },
    { 'de_art': '', 'de': 'kaufen', 'en': 'to buy', 'de_plu': '' },
    { 'de_art': '', 'de': 'kommen', 'en': 'to come', 'de_plu': '' },
    { 'de_art': '', 'de': 'kosten', 'en': 'to cost', 'de_plu': '' },
    { 'de_art': '', 'de': 'lesen', 'en': 'to read', 'de_plu': '' },
    { 'de_art': '', 'de': 'lieben', 'en': 'to love', 'de_plu': '' },
    { 'de_art': '', 'de': 'machen', 'en': 'to make, do', 'de_plu': '' },
    { 'de_art': '', 'de': 'nehmen', 'en': 'to take', 'de_plu': '' },
    { 'de_art': '', 'de': 'öffnen', 'en': 'to open', 'de_plu': '' },
    { 'de_art': '', 'de': 'probieren', 'en': 'to try (out)', 'de_plu': '' },
    { 'de_art': '', 'de': 'regnen', 'en': 'to rain', 'de_plu': '' },
    { 'de_art': '', 'de': 'reisen', 'en': 'to travel', 'de_plu': '' },
    { 'de_art': '', 'de': 'sagen', 'en': 'to say, tell', 'de_plu': '' },
    { 'de_art': '', 'de': 'schlafen', 'en': 'to sleep', 'de_plu': '' },
    { 'de_art': '', 'de': 'schmecken', 'en': 'to taste, be tasty', 'de_plu': '' },
    { 'de_art': '', 'de': 'schreiben', 'en': 'to write', 'de_plu': '' },
    { 'de_art': '', 'de': 'schwimmen', 'en': 'to swim', 'de_plu': '' },
    { 'de_art': '', 'de': 'sehen', 'en': 'to see', 'de_plu': '' },
    { 'de_art': '', 'de': 'senden', 'en': 'to send, transmit', 'de_plu': '' },
    { 'de_art': '', 'de': 'setzen', 'en': 'to put, set', 'de_plu': '' },
    { 'de_art': '', 'de': 'singen', 'en': 'to sing', 'de_plu': '' },
    { 'de_art': '', 'de': 'spielen', 'en': 'to play, act', 'de_plu': '' },
    { 'de_art': '', 'de': 'sprechen', 'en': 'to speak', 'de_plu': '' },
    { 'de_art': '', 'de': 'suchen', 'en': 'to seek, search look for', 'de_plu': '' },
    { 'de_art': '', 'de': 'trinken', 'en': 'to drink', 'de_plu': '' },
    { 'de_art': '', 'de': 'vergessen', 'en': 'to forget', 'de_plu': '' },
    { 'de_art': '', 'de': 'verstehen', 'en': 'to understand', 'de_plu': '' },
    { 'de_art': '', 'de': 'warten', 'en': 'to wait', 'de_plu': '' },
    { 'de_art': '', 'de': 'wohnen', 'en': 'to reside, live (in)', 'de_plu': '' },
    { 'de_art': '', 'de': 'zeigen', 'en': 'to show, indicate', 'de_plu': '' },
]