export const vocabulary = [
    //Colors
    { 'de': 'rot', 'en': 'red' },
    { 'de': 'rosa', 'en': 'pink' },
    { 'de': 'blau', 'en': 'blue' },
    { 'de': 'grün', 'en': 'green' },
    { 'de': 'gelb', 'en': 'yellow' },
    { 'de': 'orange', 'en': 'orange' },
    { 'de': 'braun', 'en': 'brown' },
    { 'de': 'weiß', 'en': 'white' },
    { 'de': 'schwarz', 'en': 'black' },
    { 'de': 'grau', 'en': 'gray' },
    { 'de': 'silber', 'en': 'silver' },

    //Weekdays
    { 'de': 'Montag', 'en': 'Monday' },
    { 'de': 'Dienstag', 'en': 'Tuesday' },
    { 'de': 'Mittwoch', 'en': 'Wednesday' },
    { 'de': 'Donnerstag', 'en': 'Thursday' },
    { 'de': 'Freitag', 'en': 'Friday' },
    { 'de': 'Samstag', 'en': 'Saturday' },
    { 'de': 'Sonntag', 'en': 'Sunday' },

    //Fruit
    { 'de_art': 'der', 'de': 'Apfel', 'en': 'apple', 'de_plu': 'die Äpfel' },
    { 'de_art': 'die', 'de': 'Ananas', 'en': 'pineapple', 'de_plu': 'die Ananasse' },
    { 'de_art': 'die', 'de': 'Banane', 'en': 'banana', 'de_plu': 'die Bananen' },
    { 'de_art': 'die', 'de': 'Birne', 'en': 'pear', 'de_plu': 'die Birnen' },
    { 'de_art': 'die', 'de': 'Erdbeere', 'en': 'strawberry', 'de_plu': 'die Erdbeeren' },
    { 'de_art': 'die', 'de': 'Kirsche', 'en': 'cherry', 'de_plu': 'die Kirschen' },
    { 'de_art': 'die', 'de': 'Melone', 'en': 'melon', 'de_plu': 'die Melonen' },
    { 'de_art': 'die', 'de': 'Orange', 'en': 'orange', 'de_plu': 'die Orangen' },
    { 'de_art': 'der', 'de': 'Pfirsich', 'en': 'peach', 'de_plu': 'die Pfirsiche' },
    { 'de_art': 'die', 'de': 'Wassermelone', 'en': 'watermelon', 'de_plu': 'die Wassermelonen' },
    { 'de_art': 'die', 'de': 'Weintraube', 'en': 'grape', 'de_plu': 'die Weintrauben' },
    { 'de_art': 'die', 'de': 'Zitrone', 'en': 'lemon', 'de_plu': 'die Zitronen' },
    //Family
    { 'de_art': 'die', 'de': 'Eltern', 'en': 'parents', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Mutter', 'en': 'mother', 'de_plu': 'die Mütter' },
    { 'de_art': 'der', 'de': 'Vater', 'en': 'father', 'de_plu': 'die Väter' },
    { 'de_art': 'die', 'de': 'Geschwister', 'en': 'siblings', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Schwester', 'en': 'sister', 'de_plu': 'die Schwestern' },
    { 'de_art': 'der', 'de': 'Bruder', 'en': 'brother', 'de_plu': 'die Brüder' },
    { 'de_art': 'die', 'de': 'Mama', 'en': 'mother (informal)', 'de_plu': 'die Mamas' },
    { 'de_art': 'die', 'de': 'Mami', 'en': 'mother (informal)', 'de_plu': 'die Mamis' },
    { 'de_art': 'die', 'de': 'Mutti', 'en': 'mother (informal)', 'de_plu': 'die Muttis' },
    { 'de_art': 'der', 'de': 'Papa', 'en': 'father (informal)', 'de_plu': 'die Papas' },
    { 'de_art': 'der', 'de': 'Papi', 'en': 'father (informal)', 'de_plu': 'die Papis' },
    { 'de_art': 'der', 'de': 'Vati', 'en': 'father (informal)', 'de_plu': 'die Vatis' },
    //Weather
    { 'de_art': 'das', 'de': 'das Gewitter', 'en': 'storm', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Graupeln (Plural) ', 'en': 'ice pellets', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Hagel', 'en': 'hail', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Himmel', 'en': 'sky', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Nebel', 'en': 'fog', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Regen', 'en': 'rain', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Regenbogen', 'en': 'rainbow', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Schnee', 'en': 'snow', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Sonne', 'en': 'sun', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Sturm', 'en': 'storm', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Tau', 'en': 'dew', 'de_plu': '' },
    { 'de_art': 'der', 'de': 'Wind', 'en': 'wind', 'de_plu': '' },
    { 'de_art': 'die', 'de': 'Wolke', 'en': 'cloud', 'de_plu': '' },
    //Parts of the house
    { 'de_art': 'das', 'de': 'Bad ', 'en': 'bathroom', 'de_plu': 'die Bäder' },
    { 'de_art': 'der', 'de': 'Balkon ', 'en': 'balcony', 'de_plu': 'die Balkone' },
    { 'de_art': 'die', 'de': 'Bibliothek ', 'en': 'library', 'de_plu': 'die Bibliotheken' },
    { 'de_art': 'die', 'de': 'Eingangshalle ', 'en': 'entry way', 'de_plu': 'die Eingangshallen' },
    { 'de_art': 'der', 'de': 'Flur ', 'en': 'hall', 'de_plu': 'die Flure' },
    { 'de_art': 'der', 'de': 'Garten ', 'en': 'garden', 'de_plu': 'die Gärten' },
    { 'de_art': 'das', 'de': 'Gästezimmer ', 'en': 'guest room', 'de_plu': 'die Gästezimmer' },
    { 'de_art': 'der', 'de': 'Keller ', 'en': 'basement', 'de_plu': 'die Keller' },
    { 'de_art': 'das', 'de': 'Kinderzimmer ', 'en': 'kid’s room', 'de_plu': 'die Kinderzimmer' },
    { 'de_art': 'die', 'de': 'Küche ', 'en': 'kitchen', 'de_plu': 'die Küchen' },
    { 'de_art': 'das', 'de': 'Esszimmer', 'en': 'dining room', 'de_plu': 'die Esszimmer' },
    { 'de_art': 'die', 'de': 'Toilette ', 'en': 'toilet', 'de_plu': 'die Toiletten' },
    { 'de_art': 'der', 'de': 'Weinkeller ', 'en': 'wine cellar', 'de_plu': 'die Weinkeller' },
    { 'de_art': 'das', 'de': 'Wohnzimmer ', 'en': 'living room', 'de_plu': 'die Wohnzimmer' },
    { 'de_art': 'das', 'de': 'Schlafzimmer', 'en': 'bedroom', 'de_plu': 'die Schlafzimmer' },

]